# golangci-lint configuration file
# See https://golangci-lint.run/usage/configuration/ for more information

version: 2

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  lll:
    line-length: 120
  misspell:
    locale: US

formatters:
  enable:
    - gofmt
    - goimports

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0

